[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "calculator"
version = "0.1.0"
description = "A simple CLI calculator"
authors = [{name="Nishita Nadimpalli"}]
dependencies = []
